from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

from analyze import build_stage_tensor_io


DISPATCH_SCRIPT_DIR = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = DISPATCH_SCRIPT_DIR / "templates/small_tensor_flow"


def write_config(
    path: Path,
    small_config: dict[str, int],
    event_id: str,
    features: dict[str, object] | None = None,
) -> None:
    expected_stages = tuple((features or {}).get("expected_stages", ())) or (
        "input_rmsnorm",
        "qkv_projection",
        "rope",
        "attention",
        "visual_adjust",
        "attention_output",
        "mlp",
    )
    visual_adjust_kind = (features or {}).get("visual_adjust_kind")
    prune_probe_kind = (features or {}).get("prune_probe_kind")
    path.write_text(
        "\n".join(
            [
                "from __future__ import annotations",
                "",
                "from dataclasses import dataclass",
                "",
                "",
                "@dataclass(frozen=True)",
                "class FlowConfig:",
                f"    seq: int = {small_config['seq']}",
                f"    q_seq: int = {small_config.get('q_seq', small_config['seq'])}",
                f"    kv_seq: int = {small_config.get('kv_seq', small_config['seq'])}",
                f"    hidden: int = {small_config['hidden']}",
                f"    heads: int = {small_config['heads']}",
                f"    head_dim: int = {small_config['head_dim']}",
                f"    visual_start: int = {small_config['visual_start']}",
                f"    visual_end: int = {small_config['visual_end']}",
                f"    tail_start: int = {small_config['tail_start']}",
                f"    ffn: int = {small_config['ffn']}",
                "    eps: float = 1e-5",
                "    weight_seed: int = 7",
                "    input_seed: int = 11",
                f"    event_id: str = {event_id!r}",
                "",
                "    @property",
                "    def half_dim(self) -> int:",
                "        return self.head_dim // 2",
                "",
                "    @property",
                "    def visual_tokens(self) -> int:",
                "        return self.visual_end - self.visual_start",
                "",
                "    @property",
                "    def tail_tokens(self) -> int:",
                "        return self.seq - self.tail_start",
                "",
                "",
                f"EXPECTED_STAGES = {expected_stages!r}",
                f"VISUAL_ADJUST_KIND = {visual_adjust_kind!r}",
                f"PRUNE_PROBE_KIND = {prune_probe_kind!r}",
                "",
                "CFG = FlowConfig()",
                "",
            ]
        ),
        encoding="utf-8",
    )


def copy_flow_template(
    destination: Path,
    event_id: str,
    small_config: dict[str, int],
    features: dict[str, object] | None = None,
) -> None:
    if not TEMPLATE_DIR.exists():
        raise FileNotFoundError(f"Small tensor flow template not found: {TEMPLATE_DIR}")
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)
    for source in TEMPLATE_DIR.iterdir():
        if source.name in {"__pycache__", "onnx"}:
            continue
        target = destination / source.name
        if source.is_dir():
            shutil.copytree(source, target, ignore=shutil.ignore_patterns("__pycache__"))
        elif source.suffix == ".py" or source.name == "README.md":
            shutil.copy2(source, target)
    write_config(destination / "config.py", small_config, event_id, features)
    readme = destination / "README.md"
    readme.write_text(
        "\n".join(
            [
                f"# {event_id} Small Tensor Flow",
                "",
                "Generated by `dispatch/layer_pipeline/run.py`.",
                "",
                "Run the value-level torch flow:",
                "",
                "```bash",
                f"python {destination / 'run_full_flow.py'}",
                "```",
                "",
                "Export per-stage ONNX:",
                "",
                "```bash",
                f"python {destination / 'export_stage_onnx.py'}",
                "```",
                "",
                "The ONNX files are written to `onnx/` inside this directory.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def export_stage_onnx(flow_dir: Path, onnx_out_dir: Path) -> None:
    flow_dir = flow_dir.resolve()
    onnx_out_dir = onnx_out_dir.resolve()
    if onnx_out_dir.exists():
        shutil.rmtree(onnx_out_dir)
    subprocess.run(
        [sys.executable, str(flow_dir / "export_stage_onnx.py"), "--out-dir", str(onnx_out_dir)],
        check=True,
        cwd=str(flow_dir),
    )


def _json_blob(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True)


def _strip_generated_indent(source: str) -> str:
    lines = source.splitlines()
    stripped = [line[8:] if line.startswith("        ") else line for line in lines]
    return "\n".join(stripped) + "\n"


def _shape_comment(stage: str, dims: dict[str, int | None], features: dict[str, object]) -> str:
    hidden = dims.get("hidden")
    heads = dims.get("heads")
    head_dim = dims.get("head_dim")
    q_len = features.get("q_len")
    kv_len = features.get("kv_len")
    if stage == "input_rmsnorm":
        return f"hidden_states: [{q_len}, {hidden}] -> normalized [{q_len}, {hidden}]"
    if stage == "qkv_projection":
        return f"Q/K/V projection: [{q_len}, {hidden}] -> [{heads}, {q_len}, {head_dim}]"
    if stage == "kv_cache_concat":
        return f"decode cache concat: current K/V plus past cache -> [{heads}, {kv_len}, {head_dim}]"
    if stage == "attention":
        return f"attention scores: [{heads}, {q_len}, {kv_len}]"
    if stage == "attention_output":
        return f"attention output: [{heads}, {q_len}, {head_dim}] -> [{q_len}, {hidden}]"
    if stage == "mlp":
        return f"MLP: [{q_len}, {hidden}] -> [{q_len}, {hidden}]"
    return "see dispatch evidence for exact tensor roles"


def _dispatch_reconstruction_source(
    event_id: str,
    summary: dict[str, object],
    dims: dict[str, int | None],
    features: dict[str, object],
    core_evidence: dict[str, object],
) -> str:
    expected_stages = list(features.get("expected_stages", []))
    stage_comments = "\n".join(
        f"# - {stage}: {_shape_comment(stage, dims, features)}" for stage in expected_stages
    )
    return _strip_generated_indent(textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        """Torch reconstruction scaffold for {event_id}, derived from dispatch evidence.

        This file preserves the original layer's dispatch-derived process and tensor
        roles. It is meant for reading, adaptation, and cross-checking against the
        dispatch CSV; use `toy_tensor_compute.py` for a runnable small-shape version.
        """

        from __future__ import annotations

        import json
        import torch
        import torch.nn.functional as F


        EVENT_ID = {event_id!r}
        ORIGINAL_DIMS = json.loads(r"""{_json_blob(dims)}""")
        DISPATCH_FEATURES = json.loads(r"""{_json_blob(features)}""")
        CORE_EVIDENCE = json.loads(r"""{_json_blob(core_evidence)}""")
        SUMMARY = json.loads(r"""{_json_blob(summary)}""")
        EXPECTED_STAGES = DISPATCH_FEATURES["expected_stages"]

        {stage_comments}


        def rms_norm(hidden_states: torch.Tensor, weight: torch.Tensor, eps: float = 1e-5) -> dict[str, torch.Tensor]:
            x_float = hidden_states.to(torch.float32)
            squared = x_float.pow(2)
            variance = squared.mean(dim=-1, keepdim=True)
            inv_rms = torch.rsqrt(variance + eps)
            output = (x_float * inv_rms).to(hidden_states.dtype) * weight
            return {{
                "squared": squared,
                "variance": variance,
                "inv_rms": inv_rms,
                "output": output,
            }}


        def split_heads(x: torch.Tensor, heads: int, head_dim: int) -> torch.Tensor:
            return x.view(x.shape[0], heads, head_dim).transpose(0, 1)


        def qkv_projection(x_norm: torch.Tensor, weights: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
            heads = int(ORIGINAL_DIMS["heads"])
            head_dim = int(ORIGINAL_DIMS["head_dim"])
            q_linear = F.linear(x_norm, weights["q_weight"])
            k_linear = F.linear(x_norm, weights["k_weight"])
            v_linear = F.linear(x_norm, weights["v_weight"])
            return {{
                "q_linear": q_linear,
                "k_linear": k_linear,
                "v_linear": v_linear,
                "q_heads": split_heads(q_linear, heads, head_dim),
                "k_heads_current": split_heads(k_linear, heads, head_dim),
                "v_heads_current": split_heads(v_linear, heads, head_dim),
            }}


        def rotate_half(x: torch.Tensor) -> torch.Tensor:
            half = x.shape[-1] // 2
            return torch.cat((-x[..., half:], x[..., :half]), dim=-1)


        def apply_rope(heads_tensor: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor, position_ids: torch.Tensor) -> torch.Tensor:
            cos_for_pos = cos.index_select(0, position_ids).unsqueeze(0)
            sin_for_pos = sin.index_select(0, position_ids).unsqueeze(0)
            return (heads_tensor * cos_for_pos) + (rotate_half(heads_tensor) * sin_for_pos)


        def kv_cache_concat(
            k_current: torch.Tensor,
            v_current: torch.Tensor,
            past_k: torch.Tensor | None = None,
            past_v: torch.Tensor | None = None,
        ) -> tuple[torch.Tensor, torch.Tensor]:
            if "kv_cache_concat" not in EXPECTED_STAGES:
                return k_current, v_current
            if past_k is None or past_v is None:
                raise ValueError("dispatch expects kv_cache_concat; provide past_k and past_v")
            return torch.cat((past_k, k_current), dim=-2), torch.cat((past_v, v_current), dim=-2)


        def attention(q_rope: torch.Tensor, k_rope: torch.Tensor, attention_mask: torch.Tensor) -> dict[str, torch.Tensor]:
            raw_scores = torch.matmul(q_rope, k_rope.transpose(-2, -1))
            scaled_scores = raw_scores / (q_rope.shape[-1] ** 0.5)
            masked_scores = scaled_scores + attention_mask
            attn = torch.softmax(masked_scores, dim=-1)
            return {{
                "raw_scores": raw_scores,
                "scaled_scores": scaled_scores,
                "masked_scores": masked_scores,
                "attn": attn,
            }}


        def visual_adjust(attn: torch.Tensor, visual_start: int, visual_end: int, tail_start: int) -> dict[str, torch.Tensor]:
            kind = DISPATCH_FEATURES.get("visual_adjust_kind")
            adjusted = attn.clone()
            if kind is None:
                return {{"adjusted_attn": adjusted}}
            adjusted[..., visual_start:, visual_start:visual_end] = 0
            if kind == "fold_tail_visual_mass_and_clear_region":
                tail_visual_sum = attn[..., tail_start:, visual_start:visual_end].sum(dim=-1)
                adjusted[..., tail_start:, visual_start] = tail_visual_sum
                return {{"adjusted_attn": adjusted, "tail_visual_sum": tail_visual_sum}}
            return {{"adjusted_attn": adjusted}}


        def visipruner_similarity_check(reference: torch.Tensor, candidate: torch.Tensor) -> dict[str, torch.Tensor]:
            similarity = F.cosine_similarity(reference, candidate, dim=-1)
            threshold = torch.tensor(0.9, dtype=similarity.dtype, device=similarity.device)
            return {{"similarity": similarity, "any_close": torch.any(similarity > threshold)}}


        def attention_output(
            attn: torch.Tensor,
            v_heads: torch.Tensor,
            hidden_states: torch.Tensor,
            weights: dict[str, torch.Tensor],
        ) -> dict[str, torch.Tensor]:
            context_heads = torch.matmul(attn, v_heads)
            context = context_heads.transpose(0, 1).contiguous().reshape(hidden_states.shape[0], -1)
            attn_out = F.linear(context, weights["o_weight"])
            after_attn = hidden_states + attn_out
            return {{"context": context, "attn_out": attn_out, "after_attn": after_attn}}


        def mlp(after_attn: torch.Tensor, weights: dict[str, torch.Tensor], post_norm_weight: torch.Tensor) -> dict[str, torch.Tensor]:
            post_norm = rms_norm(after_attn, post_norm_weight)
            gate = F.linear(post_norm["output"], weights["gate_weight"])
            up = F.linear(post_norm["output"], weights["up_weight"])
            gated = F.silu(gate) * up
            ffn_out = F.linear(gated, weights["down_weight"])
            output = after_attn + ffn_out
            return {{"post_norm": post_norm["output"], "gated": gated, "ffn_out": ffn_out, "output": output}}


        def expected_stage_evidence() -> dict[str, object]:
            return {{stage: CORE_EVIDENCE.get(stage, {{}}) for stage in EXPECTED_STAGES}}
        '''
    ))


def _toy_tensor_compute_source(
    event_id: str,
    small_config: dict[str, int],
    dims: dict[str, int | None],
    features: dict[str, object],
    core_evidence: dict[str, object],
) -> str:
    return _strip_generated_indent(textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        """Runnable small-shape toy tensor process for {event_id}.

        The code keeps the dispatch-derived stage order and optional stages, but
        shrinks tensor sizes for inspection and ONNX/debugger-friendly execution.
        Batch dimension is intentionally omitted because the traced batch is fixed
        to one.
        """

        from __future__ import annotations

        import argparse
        import json
        import torch
        import torch.nn.functional as F


        EVENT_ID = {event_id!r}
        SMALL_CONFIG = json.loads(r"""{_json_blob(small_config)}""")
        ORIGINAL_DIMS = json.loads(r"""{_json_blob(dims)}""")
        DISPATCH_FEATURES = json.loads(r"""{_json_blob(features)}""")
        CORE_EVIDENCE = json.loads(r"""{_json_blob(core_evidence)}""")
        EXPECTED_STAGES = DISPATCH_FEATURES["expected_stages"]


        def _cfg(name: str) -> int:
            return int(SMALL_CONFIG[name])


        def _randn(generator: torch.Generator, *shape: int, scale: float = 0.08) -> torch.Tensor:
            return torch.randn(*shape, generator=generator, dtype=torch.float32) * scale


        def q_seq() -> int:
            return _cfg("q_seq")


        def kv_seq() -> int:
            return _cfg("kv_seq")


        def make_inputs() -> dict[str, torch.Tensor]:
            generator = torch.Generator(device="cpu").manual_seed(11)
            q = q_seq()
            kv = kv_seq()
            hidden_states = torch.randn(q, _cfg("hidden"), generator=generator, dtype=torch.float32)
            position_ids = torch.arange(max(kv - q, 0), kv, dtype=torch.long)
            key_positions = torch.arange(kv, dtype=torch.long)
            future = key_positions.unsqueeze(0) > position_ids.unsqueeze(1)
            attention_mask = future.to(torch.float32).masked_fill(future, -10000.0)
            past_tokens = max(kv - q, 0)
            past_k = _randn(generator, _cfg("heads"), past_tokens, _cfg("head_dim")) if past_tokens else torch.empty(_cfg("heads"), 0, _cfg("head_dim"))
            past_v = _randn(generator, _cfg("heads"), past_tokens, _cfg("head_dim")) if past_tokens else torch.empty(_cfg("heads"), 0, _cfg("head_dim"))
            return {{
                "hidden_states": hidden_states,
                "position_ids": position_ids,
                "attention_mask": attention_mask,
                "past_k": past_k,
                "past_v": past_v,
            }}


        def make_weights() -> dict[str, torch.Tensor]:
            generator = torch.Generator(device="cpu").manual_seed(7)
            return {{
                "input_norm_weight": torch.ones(_cfg("hidden"), dtype=torch.float32),
                "post_norm_weight": torch.ones(_cfg("hidden"), dtype=torch.float32),
                "q_weight": _randn(generator, _cfg("hidden"), _cfg("hidden")),
                "k_weight": _randn(generator, _cfg("hidden"), _cfg("hidden")),
                "v_weight": _randn(generator, _cfg("hidden"), _cfg("hidden")),
                "o_weight": _randn(generator, _cfg("hidden"), _cfg("hidden")),
                "gate_weight": _randn(generator, _cfg("ffn"), _cfg("hidden")),
                "up_weight": _randn(generator, _cfg("ffn"), _cfg("hidden")),
                "down_weight": _randn(generator, _cfg("hidden"), _cfg("ffn")),
            }}


        def rope_cache() -> dict[str, torch.Tensor]:
            positions = torch.arange(kv_seq(), dtype=torch.float32).unsqueeze(1)
            freqs = torch.arange(_cfg("head_dim"), dtype=torch.float32).unsqueeze(0)
            angles = positions / (10000.0 ** (freqs / _cfg("head_dim")))
            return {{"cos": torch.cos(angles), "sin": torch.sin(angles)}}


        def rms_norm(hidden_states: torch.Tensor, weight: torch.Tensor, eps: float = 1e-5) -> dict[str, torch.Tensor]:
            x_float = hidden_states.to(torch.float32)
            squared = x_float.pow(2)
            variance = squared.mean(dim=-1, keepdim=True)
            inv_rms = torch.rsqrt(variance + eps)
            output = (x_float * inv_rms).to(hidden_states.dtype) * weight
            return {{"squared": squared, "variance": variance, "inv_rms": inv_rms, "output": output}}


        def split_heads(x: torch.Tensor) -> torch.Tensor:
            return x.view(x.shape[0], _cfg("heads"), _cfg("head_dim")).transpose(0, 1)


        def project_qkv(x_norm: torch.Tensor, weights: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
            q_linear = F.linear(x_norm, weights["q_weight"])
            k_linear = F.linear(x_norm, weights["k_weight"])
            v_linear = F.linear(x_norm, weights["v_weight"])
            return {{
                "q_linear": q_linear,
                "k_linear": k_linear,
                "v_linear": v_linear,
                "q_heads": split_heads(q_linear),
                "k_heads_current": split_heads(k_linear),
                "v_heads_current": split_heads(v_linear),
            }}


        def rotate_half(x: torch.Tensor) -> torch.Tensor:
            half = x.shape[-1] // 2
            return torch.cat((-x[..., half:], x[..., :half]), dim=-1)


        def apply_rope_to_heads(heads_tensor: torch.Tensor, positions: torch.Tensor, cache: dict[str, torch.Tensor]) -> torch.Tensor:
            cos = cache["cos"].index_select(0, positions).unsqueeze(0)
            sin = cache["sin"].index_select(0, positions).unsqueeze(0)
            return (heads_tensor * cos) + (rotate_half(heads_tensor) * sin)


        def kv_cache_concat(k_current: torch.Tensor, v_current: torch.Tensor, inputs: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
            if "kv_cache_concat" not in EXPECTED_STAGES:
                return {{"k_heads": k_current, "v_heads": v_current}}
            return {{
                "k_heads": torch.cat((inputs["past_k"], k_current), dim=-2),
                "v_heads": torch.cat((inputs["past_v"], v_current), dim=-2),
            }}


        def attention(q_rope: torch.Tensor, k_rope: torch.Tensor, attention_mask: torch.Tensor) -> dict[str, torch.Tensor]:
            raw_scores = torch.matmul(q_rope, k_rope.transpose(-2, -1))
            scaled_scores = raw_scores / (_cfg("head_dim") ** 0.5)
            masked_scores = scaled_scores + attention_mask
            attn = torch.softmax(masked_scores, dim=-1)
            return {{"raw_scores": raw_scores, "scaled_scores": scaled_scores, "masked_scores": masked_scores, "attn": attn}}


        def visual_adjust(attn: torch.Tensor) -> dict[str, torch.Tensor]:
            kind = DISPATCH_FEATURES.get("visual_adjust_kind")
            adjusted = attn.clone()
            if kind is None:
                return {{"adjusted_attn": adjusted}}
            q_visual_start = min(_cfg("visual_start"), adjusted.shape[-2])
            q_tail_start = min(_cfg("tail_start"), adjusted.shape[-2])
            k_visual_start = min(_cfg("visual_start"), adjusted.shape[-1])
            k_visual_end = min(_cfg("visual_end"), adjusted.shape[-1])
            if q_visual_start < adjusted.shape[-2] and k_visual_start < k_visual_end:
                adjusted[..., q_visual_start:, k_visual_start:k_visual_end] = 0.0
            result = {{"adjusted_attn": adjusted}}
            if kind == "fold_tail_visual_mass_and_clear_region" and q_tail_start < adjusted.shape[-2] and k_visual_start < k_visual_end:
                tail_visual_sum = attn[..., q_tail_start:, k_visual_start:k_visual_end].sum(dim=-1)
                adjusted[..., q_tail_start:, k_visual_start] = tail_visual_sum
                result["tail_visual_sum"] = tail_visual_sum
            return result


        def visipruner_similarity_check(hidden_states: torch.Tensor) -> dict[str, torch.Tensor]:
            if "visipruner_similarity_check" not in EXPECTED_STAGES:
                empty = torch.empty(0, dtype=hidden_states.dtype)
                return {{"similarity": empty, "any_close": torch.tensor(False)}}
            if hidden_states.shape[0] < 2:
                reference = hidden_states
                candidate = hidden_states
            else:
                reference = hidden_states[:-1]
                candidate = hidden_states[1:]
            similarity = F.cosine_similarity(reference, candidate, dim=-1)
            return {{"similarity": similarity, "any_close": torch.any(similarity > 0.9)}}


        def attention_output(attn: torch.Tensor, v_heads: torch.Tensor, hidden_states: torch.Tensor, weights: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
            context_heads = torch.matmul(attn, v_heads)
            context = context_heads.transpose(0, 1).contiguous().reshape(hidden_states.shape[0], _cfg("hidden"))
            attn_out = F.linear(context, weights["o_weight"])
            after_attn = hidden_states + attn_out
            return {{"context_heads": context_heads, "context": context, "attn_out": attn_out, "after_attn": after_attn}}


        def gated_mlp(after_attn: torch.Tensor, weights: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
            post_norm = rms_norm(after_attn, weights["post_norm_weight"])
            gate = F.linear(post_norm["output"], weights["gate_weight"])
            up = F.linear(post_norm["output"], weights["up_weight"])
            gated = F.silu(gate) * up
            ffn_out = F.linear(gated, weights["down_weight"])
            output = after_attn + ffn_out
            return {{"post_norm_output": post_norm["output"], "gate": gate, "up": up, "gated": gated, "ffn_out": ffn_out, "output": output}}


        def run_toy_flow() -> dict[str, torch.Tensor]:
            inputs = make_inputs()
            weights = make_weights()
            cache = rope_cache()
            tensors: dict[str, torch.Tensor] = dict(inputs)
            input_norm = rms_norm(inputs["hidden_states"], weights["input_norm_weight"])
            tensors.update({{"input_norm_output": input_norm["output"], "input_norm_variance": input_norm["variance"]}})
            qkv = project_qkv(input_norm["output"], weights)
            tensors.update(qkv)
            q_rope = apply_rope_to_heads(qkv["q_heads"], inputs["position_ids"], cache)
            k_current_rope = apply_rope_to_heads(qkv["k_heads_current"], inputs["position_ids"], cache)
            tensors.update({{"q_rope": q_rope, "k_current_rope": k_current_rope}})
            kv = kv_cache_concat(k_current_rope, qkv["v_heads_current"], inputs)
            tensors.update(kv)
            attn = attention(q_rope, kv["k_heads"], inputs["attention_mask"])
            tensors.update(attn)
            if "visual_adjust" in EXPECTED_STAGES:
                adjusted = visual_adjust(attn["attn"])
                tensors.update(adjusted)
                attn_for_output = adjusted["adjusted_attn"]
            else:
                tensors["adjusted_attn"] = attn["attn"]
                attn_for_output = attn["attn"]
            if "visipruner_similarity_check" in EXPECTED_STAGES:
                tensors.update(visipruner_similarity_check(inputs["hidden_states"]))
            attn_out = attention_output(attn_for_output, kv["v_heads"], inputs["hidden_states"], weights)
            tensors.update(attn_out)
            mlp_out = gated_mlp(attn_out["after_attn"], weights)
            tensors.update(mlp_out)
            return tensors


        def _describe(name: str, tensor: torch.Tensor) -> str:
            return f"{{name}}: shape={{tuple(tensor.shape)}} dtype={{str(tensor.dtype).replace('torch.', '')}}"


        def main() -> None:
            parser = argparse.ArgumentParser(description=__doc__)
            parser.add_argument("--quiet", action="store_true")
            args = parser.parse_args()
            with torch.no_grad():
                tensors = run_toy_flow()
            if not args.quiet:
                print(f"event_id={{EVENT_ID}}")
                print(f"expected_stages={{', '.join(EXPECTED_STAGES)}}")
                for name, tensor in tensors.items():
                    if isinstance(tensor, torch.Tensor):
                        print(_describe(name, tensor))


        if __name__ == "__main__":
            main()
        '''
    ))


def _process_index_markdown(
    event_id: str,
    process_manifest: dict[str, object],
    features: dict[str, object],
    core_evidence: dict[str, object],
) -> str:
    lines = [
        f"# {event_id} Process Code Index",
        "",
        "The ONNX files in this layer are final visualization outputs. The files below are the process outputs used to inspect or regenerate the layer-specific computation.",
        "",
        "## Code Artifacts",
        "",
        f"- dispatch reconstruction: `{process_manifest['dispatch_reconstruction']}`",
        f"- runnable toy process: `{process_manifest['toy_tensor_compute']}`",
        f"- split small-tensor torch flow: `{process_manifest['torch_flow_dir']}`",
        "",
        "## Dispatch-Derived Stage Order",
        "",
    ]
    for index, stage in enumerate(features.get("expected_stages", []), start=1):
        lines.append(f"{index}. `{stage}`")
    stage_tensor_io = process_manifest.get("stage_tensor_io", {})
    if isinstance(stage_tensor_io, dict):
        lines.extend(["", "## Dispatch Tensor ID Stage I/O", ""])
        for stage in features.get("expected_stages", []):
            item = stage_tensor_io.get(stage, {})
            if not isinstance(item, dict):
                continue
            inputs = ", ".join(str(value) for value in item.get("input_tensor_ids", [])[:12])
            outputs = ", ".join(str(value) for value in item.get("output_tensor_ids", [])[:12])
            lines.append(f"- `{stage}` inputs: `{inputs}`")
            lines.append(f"- `{stage}` outputs: `{outputs}`")
    op_coverage = process_manifest.get("dispatch_op_coverage", {})
    if isinstance(op_coverage, dict):
        summary = op_coverage.get("summary", {}) if isinstance(op_coverage.get("summary", {}), dict) else {}
        lines.extend([
            "",
            "## Complete Dispatch Op Coverage",
            "",
            f"- coverage json: `{op_coverage.get('dispatch_op_coverage_json', '')}`",
            f"- coverage csv: `{op_coverage.get('dispatch_op_coverage_csv', '')}`",
            f"- coverage markdown: `{op_coverage.get('dispatch_op_coverage_markdown', '')}`",
            f"- ops in dispatch rows: `{summary.get('op_count', '')}`",
            f"- ops listed in coverage: `{summary.get('covered_op_count', '')}`",
            f"- missing event_op_index values: `{summary.get('missing_event_op_indices', [])}`",
            f"- missing from module_split: `{summary.get('missing_from_module_split', [])}`",
            f"- missing from tensor_dataflow: `{summary.get('missing_from_tensor_dataflow', [])}`",
        ])
        ops = op_coverage.get("ops", [])
        if isinstance(ops, list):
            lines.extend([
                "",
                "| # | Op | Runtime subprocess | Module split | Tensor dataflow | Stage evidence |",
                "|---:|---|---|---|---|---|",
            ])
            for item in ops:
                if not isinstance(item, dict):
                    continue
                lines.append(
                    "| {idx} | `{op}` | `{subprocess}` | `{module}` | `{dataflow}` | `{stages}` |".format(
                        idx=item.get("event_op_index", ""),
                        op=item.get("op_name", ""),
                        subprocess=item.get("runtime_subprocess", ""),
                        module=item.get("module_split_covered", ""),
                        dataflow=item.get("tensor_dataflow_covered", ""),
                        stages=", ".join(str(value) for value in item.get("stage_evidence", [])),
                    )
                )
    lines.extend(["", "## Evidence Rows", ""])
    for stage, evidence in core_evidence.items():
        lines.append(f"### `{stage}`")
        rows = evidence.get("evidence_ops", []) if isinstance(evidence, dict) else []
        if not rows:
            lines.append("- none")
        for item in rows:
            lines.append(
                f"- `#{item['event_op_index']} {item['op_name']}` "
                f"inputs=`{item.get('input_tensor_ids', [])}` outputs=`{item.get('output_tensor_ids', [])}` -> {item['output']}"
            )
        lines.append("")
    return "\n".join(lines)


ONNX_STAGE_INFO = {
    "input_rmsnorm": {
        "title": "Input RMSNorm",
        "primary_files": ["rmsnorm.py"],
        "export_class": "InputRMSNormStage",
        "explanation": "Normalizes the incoming hidden states with RMSNorm and exposes variance/inverse-RMS tensors for inspection.",
    },
    "qkv_projection": {
        "title": "Q/K/V Projection",
        "primary_files": ["qkv_projection.py"],
        "export_class": "QKVProjectionStage",
        "explanation": "Applies the query/key/value linear projections and reshapes the projected hidden states into attention heads.",
    },
    "rope": {
        "title": "RoPE",
        "primary_files": ["rope.py"],
        "export_class": "RoPEStage",
        "explanation": "Gathers rotary-position cos/sin values and applies rotate-half RoPE to query and key heads.",
    },
    "kv_cache_concat": {
        "title": "K/V Cache Concatenation",
        "primary_files": ["kv_cache.py"],
        "export_class": "KVCacheConcatStage",
        "explanation": "Concatenates past decode K/V cache with the current token's K/V heads before rectangular attention.",
    },
    "attention": {
        "title": "Scaled Dot-Product Attention",
        "primary_files": ["attention.py"],
        "export_class": "AttentionStage",
        "explanation": "Computes rectangular or square attention scores, applies the mask, and materializes softmax attention probabilities.",
    },
    "visual_adjust": {
        "title": "Visual Attention Adjustment",
        "primary_files": ["visual_adjust.py"],
        "export_class": "VisualAdjustStage",
        "explanation": "Models the VisiPrune visual-token attention adjustment stage when dispatch evidence shows visual-region clearing or tail-mass folding.",
    },
    "visipruner_similarity_check": {
        "title": "VisiPrune Similarity Check",
        "primary_files": ["visipruner_similarity.py"],
        "export_class": "VisiPrunerSimilarityCheckStage",
        "explanation": "Computes cosine-similarity based VisiPrune probe/check signals when dispatch contains the similarity sub-process.",
    },
    "attention_output": {
        "title": "Attention Output",
        "primary_files": ["attention_output.py"],
        "export_class": "AttentionOutputStage",
        "explanation": "Multiplies attention probabilities by value heads, merges heads back to hidden size, applies output projection, and adds the residual.",
    },
    "mlp": {
        "title": "MLP",
        "primary_files": ["mlp.py", "rmsnorm.py"],
        "export_class": "MLPStage",
        "explanation": "Runs post-attention RMSNorm, gated SiLU MLP, down projection, and residual addition.",
    },
    "full_flow": {
        "title": "Full Layer Flow",
        "primary_files": ["run_full_flow.py"],
        "export_class": "FullFlowStage",
        "explanation": "Aggregates the split small-tensor stages into one end-to-end layer flow for whole-layer visualization.",
    },
}


def _stage_from_onnx_path(path: str) -> str:
    stem = Path(path).stem
    return re.sub(r"^\d+_", "", stem)


def _extract_export_class(source: str, class_name: str) -> str:
    pattern = re.compile(
        rf"^class\s+{re.escape(class_name)}\b.*?(?=^class\s+\w+|^def\s+\w+|^if\s+__name__|\\Z)",
        flags=re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(source)
    return match.group(0).rstrip() + "\n" if match else f"# Could not find {class_name} in export_stage_onnx.py\n"


def _read_source(path: Path) -> str:
    if not path.exists():
        return f"# Missing expected source file: {path}\n"
    return path.read_text(encoding="utf-8")


def _shape_lines(values: dict[str, object]) -> list[str]:
    return [f"- `{name}`: `{shape}`" for name, shape in values.items()]


def _evidence_lines(stage: str, core_evidence: dict[str, object]) -> list[str]:
    evidence = core_evidence.get(stage, {})
    rows = evidence.get("evidence_ops", []) if isinstance(evidence, dict) else []
    if not rows:
        return ["- No direct dispatch evidence rows were assigned to this stage."]
    return [
        f"- `#{item['event_op_index']} {item['op_name']}` "
        f"inputs=`{item.get('input_tensor_ids', [])}` outputs=`{item.get('output_tensor_ids', [])}` -> {item['output']}"
        for item in rows[:20]
    ]


def _write_single_onnx_code_markdown(
    out_path: Path,
    event_id: str,
    stage: str,
    onnx_item: dict[str, object],
    flow_dir: Path,
    export_source: str,
    core_evidence: dict[str, object],
    stage_tensor_io: dict[str, dict[str, object]],
) -> dict[str, object]:
    info = ONNX_STAGE_INFO.get(stage, {
        "title": stage,
        "primary_files": [],
        "export_class": "",
        "explanation": "No stage-specific explanation is registered for this ONNX file.",
    })
    primary_files = [flow_dir / str(name) for name in info["primary_files"]]
    support_files = [flow_dir / "config.py", flow_dir / "init_data.py", flow_dir / "export_stage_onnx.py"]
    export_class = str(info.get("export_class", ""))
    if stage == "full_flow":
        inputs_for_class = onnx_item.get("inputs", {})
        if isinstance(inputs_for_class, dict) and "past_k" in inputs_for_class:
            export_class = "DecodeFullFlowStage"
    export_class_source = _extract_export_class(export_source, export_class) if export_class else ""
    evidence = _evidence_lines(stage, core_evidence)
    inputs = onnx_item.get("inputs", {}) if isinstance(onnx_item.get("inputs", {}), dict) else {}
    outputs = onnx_item.get("outputs", {}) if isinstance(onnx_item.get("outputs", {}), dict) else {}
    dispatch_tensor_io = stage_tensor_io.get(stage, {})
    dispatch_input_tensor_ids = list(dispatch_tensor_io.get("input_tensor_ids", [])) if isinstance(dispatch_tensor_io, dict) else []
    dispatch_output_tensor_ids = list(dispatch_tensor_io.get("output_tensor_ids", [])) if isinstance(dispatch_tensor_io, dict) else []
    dispatch_dependencies = list(dispatch_tensor_io.get("data_dependencies", [])) if isinstance(dispatch_tensor_io, dict) else []

    lines = [
        f"# {event_id} `{Path(str(onnx_item['path'])).name}` Code Review",
        "",
        "## ONNX Artifact",
        "",
        f"- ONNX file: `{onnx_item['path']}`",
        f"- Stage: `{stage}`",
        f"- Stage title: {info['title']}",
        f"- ONNX nodes: `{onnx_item.get('nodes')}`",
        f"- ONNX initializers: `{onnx_item.get('initializers')}`",
        "",
        "### ONNX Inputs",
        "",
        *_shape_lines(inputs),
        "",
        "### ONNX Outputs",
        "",
        *_shape_lines(outputs),
        "",
        "### Dispatch Tensor ID Inputs/Outputs",
        "",
        f"- Dispatch input tensor ids: `{dispatch_input_tensor_ids}`",
        f"- Dispatch output tensor ids: `{dispatch_output_tensor_ids}`",
        f"- Dispatch tensor-id dependencies inside evidence rows: `{dispatch_dependencies[:12]}`",
        "",
        "## Corresponding `torch_flow` Code",
        "",
        f"- Export wrapper: `{flow_dir / 'export_stage_onnx.py'}::{export_class}`",
    ]
    for path in primary_files:
        lines.append(f"- Primary implementation: `{path}`")
    lines.extend([
        f"- Support files: `{support_files[0]}`, `{support_files[1]}`, `{support_files[2]}`",
        "",
        "## Code Explanation",
        "",
        str(info["explanation"]),
        "",
        "## Review Comments",
        "",
        f"- This page binds `{Path(str(onnx_item['path'])).name}` to the exact `torch_flow` source used to define or export that ONNX stage.",
        "- The export wrapper defines the ONNX boundary: input names, output names, buffers/initializers, and the `forward()` method traced by `torch.onnx.export`.",
        "- The primary implementation file contains the small-shape tensor computation being wrapped for visualization.",
    ])
    if stage == "full_flow":
        lines.append("- `full_flow` is a convenience aggregate that calls the split stage implementations; consult the individual stage pages for per-stage dispatch evidence.")
    else:
        lines.append("- Dispatch evidence below is the core trace evidence used to justify the stage in this layer reconstruction.")
    lines.extend(["", "## Dispatch Evidence Notes", "", *evidence, "", "## Export Wrapper Source", "", "```python", export_class_source.rstrip(), "```", ""])
    for path in primary_files:
        lines.extend([
            f"## Primary Source: `{path.name}`",
            "",
            "```python",
            _read_source(path).rstrip(),
            "```",
            "",
        ])
    out_path.write_text("\n".join(lines), encoding="utf-8")

    return {
        "onnx_path": str(onnx_item["path"]),
        "onnx_file": Path(str(onnx_item["path"])).name,
        "stage": stage,
        "stage_title": info["title"],
        "code_review_markdown": str(out_path),
        "export_wrapper": {
            "file": str(flow_dir / "export_stage_onnx.py"),
            "class": export_class,
        },
        "primary_code_files": [str(path) for path in primary_files],
        "support_code_files": [str(path) for path in support_files],
        "inputs": inputs,
        "outputs": outputs,
        "dispatch_input_tensor_ids": dispatch_input_tensor_ids,
        "dispatch_output_tensor_ids": dispatch_output_tensor_ids,
        "dispatch_tensor_dependencies": dispatch_dependencies,
        "nodes": onnx_item.get("nodes"),
        "initializers": onnx_item.get("initializers"),
        "explanation": info["explanation"],
        "dispatch_evidence_count": len(_evidence_lines(stage, core_evidence)),
    }


def _mirror_onnx_code_review_into_onnx_dir(
    onnx_manifest: list[dict[str, object]],
    review_dir: Path,
    entries: list[dict[str, object]],
) -> dict[str, object] | None:
    if not onnx_manifest:
        return None
    onnx_dir = Path(str(onnx_manifest[0]["path"])).parent
    stale_nested_dir = onnx_dir / "onnx_code"
    if stale_nested_dir.exists():
        shutil.rmtree(stale_nested_dir)
    for stale_page in onnx_dir.glob("*_code.md"):
        stale_page.unlink()
    copied_pages = 0
    for source_page in sorted(review_dir.glob("*.md")):
        shutil.copy2(source_page, onnx_dir / source_page.name)
        copied_pages += 1
    for entry in entries:
        entry["onnx_sidecar_markdown"] = str(onnx_dir / Path(str(entry["code_review_markdown"])).name)
    return {
        "onnx_dir": str(onnx_dir),
        "layout": "flat",
        "pages": copied_pages,
    }


def write_onnx_code_review(
    flow_dir: Path,
    analysis_dir: Path,
    event_id: str,
    onnx_manifest: list[dict[str, object]],
    core_evidence: dict[str, object],
) -> dict[str, object] | None:
    if not onnx_manifest:
        return None

    review_dir = analysis_dir / "onnx_code"
    if review_dir.exists():
        shutil.rmtree(review_dir)
    review_dir.mkdir(parents=True, exist_ok=True)

    export_source = _read_source(flow_dir / "export_stage_onnx.py")
    stage_tensor_io = build_stage_tensor_io(core_evidence)
    entries = []
    for item in onnx_manifest:
        stage = _stage_from_onnx_path(str(item["path"]))
        out_path = review_dir / f"{Path(str(item['path'])).stem}_code.md"
        entries.append(
            _write_single_onnx_code_markdown(
                out_path=out_path,
                event_id=event_id,
                stage=stage,
                onnx_item=item,
                flow_dir=flow_dir,
                export_source=export_source,
                core_evidence=core_evidence,
                stage_tensor_io=stage_tensor_io,
            )
        )

    index_path = analysis_dir / "onnx_code_index.md"
    map_path = analysis_dir / "onnx_code_map.json"
    index_lines = [
        f"# {event_id} ONNX To Torch Flow Code Index",
        "",
        "Each ONNX file below is linked to the exact `torch_flow` code used to define or export that stage, with a per-ONNX explanation and review comments.",
        "",
        "| ONNX | Stage | Code Review | Primary Code | Export Wrapper |",
        "|---|---|---|---|---|",
    ]
    for entry in entries:
        primary = "<br>".join(f"`{Path(path).name}`" for path in entry["primary_code_files"])
        index_lines.append(
            f"| `{entry['onnx_file']}` | `{entry['stage']}` | `{entry['code_review_markdown']}` | {primary} | `{entry['export_wrapper']['class']}` |"
        )
    index_lines.append("")
    index_path.write_text("\n".join(index_lines), encoding="utf-8")
    onnx_sidecar = _mirror_onnx_code_review_into_onnx_dir(onnx_manifest, review_dir, entries)

    payload = {
        "event_id": event_id,
        "torch_flow_dir": str(flow_dir),
        "onnx_code_review_dir": str(review_dir),
        "onnx_sidecar": onnx_sidecar,
        "onnx_code_index": str(index_path),
        "stage_tensor_io": stage_tensor_io,
        "entries": entries,
    }
    map_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    payload["onnx_code_map"] = str(map_path)
    return payload


def write_process_code_outputs(
    flow_dir: Path,
    analysis_dir: Path,
    event_id: str,
    summary: dict[str, object],
    dims: dict[str, int | None],
    features: dict[str, object],
    core_evidence: dict[str, object],
    tensor_dataflow: dict[str, object],
    tensor_dataflow_outputs: dict[str, str],
    dispatch_op_coverage: dict[str, object],
    dispatch_op_coverage_outputs: dict[str, str],
) -> dict[str, object]:
    flow_dir.mkdir(parents=True, exist_ok=True)
    analysis_dir.mkdir(parents=True, exist_ok=True)

    dispatch_reconstruction = flow_dir / "dispatch_reconstructed.py"
    toy_tensor_compute = flow_dir / "toy_tensor_compute.py"
    layer_profile = flow_dir / "layer_profile.json"
    process_index = flow_dir / "process_index.md"
    analysis_manifest = analysis_dir / "process_manifest.json"
    analysis_index = analysis_dir / "process_code_index.md"

    dispatch_reconstruction.write_text(
        _dispatch_reconstruction_source(event_id, summary, dims, features, core_evidence),
        encoding="utf-8",
    )
    toy_tensor_compute.write_text(
        _toy_tensor_compute_source(event_id, summary["small_config"], dims, features, core_evidence),
        encoding="utf-8",
    )
    profile = {
        "event_id": event_id,
        "summary": summary,
        "original_dimensions": dims,
        "dispatch_features": features,
        "core_evidence": core_evidence,
        "stage_tensor_io": build_stage_tensor_io(core_evidence),
        "tensor_dataflow_summary": {
            "op_count": tensor_dataflow.get("op_count", 0),
            "edge_count": tensor_dataflow.get("edge_count", 0),
            "external_input_tensor_ids": tensor_dataflow.get("external_input_tensor_ids", []),
            "final_output_tensor_ids": tensor_dataflow.get("final_output_tensor_ids", []),
        },
        "dispatch_op_coverage_summary": {
            "op_count": dispatch_op_coverage.get("op_count", 0),
            "covered_op_count": dispatch_op_coverage.get("covered_op_count", 0),
            "missing_event_op_indices": dispatch_op_coverage.get("missing_event_op_indices", []),
            "missing_from_module_split": dispatch_op_coverage.get("missing_from_module_split", []),
            "missing_from_tensor_dataflow": dispatch_op_coverage.get("missing_from_tensor_dataflow", []),
        },
    }
    layer_profile.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")

    split_files = {
        "input_rmsnorm": str(flow_dir / "rmsnorm.py"),
        "qkv_projection": str(flow_dir / "qkv_projection.py"),
        "rope": str(flow_dir / "rope.py"),
        "kv_cache_concat": str(flow_dir / "kv_cache.py"),
        "attention": str(flow_dir / "attention.py"),
        "visual_adjust": str(flow_dir / "visual_adjust.py"),
        "visipruner_similarity_check": str(flow_dir / "visipruner_similarity.py"),
        "attention_output": str(flow_dir / "attention_output.py"),
        "mlp": str(flow_dir / "mlp.py"),
        "full_flow": str(flow_dir / "run_full_flow.py"),
        "export_stage_onnx": str(flow_dir / "export_stage_onnx.py"),
    }
    process_manifest = {
        "event_id": event_id,
        "torch_flow_dir": str(flow_dir),
        "dispatch_reconstruction": str(dispatch_reconstruction),
        "toy_tensor_compute": str(toy_tensor_compute),
        "layer_profile": str(layer_profile),
        "process_index": str(process_index),
        "split_small_tensor_files": split_files,
        "expected_stages": features.get("expected_stages", []),
        "original_dimensions": dims,
        "small_config": summary["small_config"],
        "stage_tensor_io": build_stage_tensor_io(core_evidence),
        "tensor_dataflow": {
            **tensor_dataflow_outputs,
            "op_count": tensor_dataflow.get("op_count", 0),
            "edge_count": tensor_dataflow.get("edge_count", 0),
        },
        "dispatch_op_coverage": {
            **dispatch_op_coverage_outputs,
            "summary": {
                "op_count": dispatch_op_coverage.get("op_count", 0),
                "covered_op_count": dispatch_op_coverage.get("covered_op_count", 0),
                "missing_event_op_indices": dispatch_op_coverage.get("missing_event_op_indices", []),
                "missing_from_module_split": dispatch_op_coverage.get("missing_from_module_split", []),
                "missing_from_tensor_dataflow": dispatch_op_coverage.get("missing_from_tensor_dataflow", []),
            },
            "ops": dispatch_op_coverage.get("ops", []),
        },
    }
    process_index.write_text(
        _process_index_markdown(event_id, process_manifest, features, core_evidence),
        encoding="utf-8",
    )
    analysis_manifest.write_text(json.dumps(process_manifest, indent=2) + "\n", encoding="utf-8")
    analysis_index.write_text(
        _process_index_markdown(event_id, process_manifest, features, core_evidence),
        encoding="utf-8",
    )
    return process_manifest
